export default [
  {
    id: 1,
    title: "Acabou o Chorare",
    genre: "MPB",
    band: "Novos Baianos",
    year: 1972,
    price: "137,91",
  },
  {
    id: 2,
    title: "Clube da Esquina",
    genre: "MPB",
    band: "Milton Nascimento, Lô Borges, e outros",
    year: 1972,
    price: "94,74",
  },
  {
    id: 3,
    title: "Elis & Tom",
    genre: "MPB",
    band: "Elis Regina e Tom Jobim",
    year: 1974,
    price: "79,99",
  },
  {
    id: 4,
    title: "Thriller",
    genre: "Pop",
    band: "Michael Jackson",
    year: 1982,
    price: "142,32",
  },
  {
    id: 5,
    title: "Bad",
    genre: "Pop",
    band: "Michael Jackson",
    year: 1987,
    price: "65,33",
  },
  {
    id: 6,
    title: "Kind of Blue",
    genre: "Jazz",
    band: "Miles Davis",
    year: 1959,
    price: "61,08",
  },
  {
    id: 7,
    title: "The Dark Side of the Moon",
    genre: "Rock",
    band: "Pink Floyd",
    year: 1973,
    price: "123,56",
  },
  {
    id: 8,
    title: "Abbey Road",
    genre: "Rock",
    band: "The Beatles",
    year: 1969,
    price: "66,53",
  },
  {
    id: 9,
    title: "Legend",
    genre: "Reggae",
    band: "Bob Marley & The Wailers",
    year: 1984,
    price: "114,01",
  },
  {
    id: 10,
    title: "Illmatic",
    genre: "Rap",
    band: "Nas",
    year: 1994,
    price: "138,66",
  },
  {
    id: 11,
    title: "To Pimp a Butterfly",
    genre: "Rap",
    band: "Kendrick Lamar",
    year: 2015,
    price: "102,66",
  },
  {
    id: 12,
    title: "The Miseducation of Lauryn Hill",
    genre: "R&B",
    band: "Lauryn Hill",
    year: 1998,
    price: "139,14",
  },
  {
    id: 13,
    title: "Enter the Wu-Tang (36 Chambers)",
    genre: "Hip-Hop",
    band: "Wu-Tang Clan",
    year: 1993,
    price: "50,13",
  },
  {
    id: 14,
    title: "Doo-Wops & Hooligans",
    genre: "Pop",
    band: "Bruno Mars",
    year: 2010,
    price: "107,28",
  },
  {
    id: 15,
    title: "Canta Canta, Minha Gente",
    genre: "Samba",
    band: "Martinho da Vila",
    year: 1974,
    price: "51,67",
  },
  {
    id: 16,
    title: "Construção",
    genre: "MPB",
    band: "Chico Buarque",
    year: 1974,
    price: "119,16",
  },
  {
    id: 17,
    title: "Cantar",
    genre: "MPB",
    band: "Gal Costa",
    year: 1999,
    price: "88,86",
  },
  {
    id: 18,
    title: "Blink-182",
    genre: "Rock",
    band: "Blink-182",
    year: 2003,
    price: "67,38",
  },
  {
    id: 19,
    title: "Dysphoria",
    genre: "Eletrônica",
    band: "Crywolf",
    year: 2015,
    price: "143,18",
  },
  {
    id: 20,
    title: "Skrillex and Diplo Present Jack Ü",
    genre: "Eletrônica",
    band: "Jack Ü",
    year: 2006,
    price: "117,44",
  },
];
